version: "3.9"

services:
  outhton:   
    build:
      context: .
      dockerfile: Dockerfile
    image: outhton 
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: /app/conf/conf.env
    networks:
      - app-network
    dns:
      - "8.8.8.8"
      - "8.8.4.4"

networks:
  app-network:
    driver: bridge
